### ISSUE TITLE
MQTT Door lock is required

### ISSUE THREAD

**Issue by pointlevel** [Pythm/ad-ModeManagement#2]
When leaving out the MQTT_door_lock in the configuration the app creates an error. I believe the lock functionality should be optional.

```cs
2024-11-07 22:45:50.697050 WARNING modeManage: ------------------------------------------------------------
2024-11-07 22:46:12.144354 WARNING modeManage: ------------------------------------------------------------
2024-11-07 22:46:12.144875 WARNING modeManage: Unexpected error running initialize() for modeManage
2024-11-07 22:46:12.145278 WARNING modeManage: ------------------------------------------------------------
2024-11-07 22:46:12.147290 WARNING modeManage: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/modeManagement.py", line 131, in initialize
    for door in self.MQTT_door_lock:
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModeManagement' object has no attribute 'MQTT_door_lock'
```

**Comment by pointlevel** [comment]
I think you just missed a tab in the code below:

```py
# MQTT Door lock
        if 'MQTT_door_lock' in self.args:
            self.MQTT_door_lock:list = self.args['MQTT_door_lock']
            if not self.mqtt:
                self.mqtt = self.get_plugin_api("MQTT")
            self.lastUnlockTime = datetime.datetime.now()

        for door in self.MQTT_door_lock: #<------------------------------------------ This snippet be tabbed i believe to be included in the top if-statement.
            self.mqtt.mqtt_subscribe(door)
            self.mqtt.listen_event(self.MQTT_doorlock_event, "MQTT_MESSAGE",
                topic = door,
                namespace = self.MQTT_namespace
            )
```

**Comment by Pythm** [comment]
Thank you! 

Fixed in version 0.1.5 i hope.

**Comment by pointlevel** [comment]
Sorry, but still get errors when leaving and arriving to the house. (Just walked the dog)

```csharp
2024-11-07 23:21:39.195508 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:21:39.195783 WARNING modeManage: Unexpected error in worker for App modeManage:
2024-11-07 23:21:39.196087 WARNING modeManage: Worker Ags: {'id': '816a466e04b541b6adf8ac38ffefd5d0', 'name': 'modeManage', 'objectid': 'd6fdada3a0104f528328fb504626db5d', 'type': 'state', 'function': <bound method ModeManagement.presenceChange of <modeManagement.ModeManagement object at 0x7fd7cafaa290>>, 'attribute': 'state', 'entity': 'person.micke', 'new_state': 'not_home', 'old_state': 'home', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2024-11-07 23:21:39.196317 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:21:39.197543 WARNING modeManage: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1045, in worker
    funcref(
  File "/config/apps/modeManagement.py", line 581, in presenceChange
    for door in self.MQTT_door_lock:
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModeManagement' object has no attribute 'MQTT_door_lock'

2024-11-07 23:21:39.197770 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:22:03.855985 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:22:03.856707 WARNING modeManage: Unexpected error in worker for App modeManage:
2024-11-07 23:22:03.857315 WARNING modeManage: Worker Ags: {'id': '816a466e04b541b6adf8ac38ffefd5d0', 'name': 'modeManage', 'objectid': 'd6fdada3a0104f528328fb504626db5d', 'type': 'state', 'function': <bound method ModeManagement.presenceChange of <modeManagement.ModeManagement object at 0x7fd7cafaa290>>, 'attribute': 'state', 'entity': 'person.micke', 'new_state': 'home', 'old_state': 'not_home', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2024-11-07 23:22:03.857869 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:22:03.859662 WARNING modeManage: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1045, in worker
    funcref(
  File "/config/apps/modeManagement.py", line 530, in presenceChange
    self.unlockDoor()
  File "/config/apps/modeManagement.py", line 398, in unlockDoor
    for door in self.MQTT_door_lock:
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModeManagement' object has no attribute 'MQTT_door_lock'

2024-11-07 23:22:03.860196 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:23:39.201811 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:23:39.202418 WARNING modeManage: Unexpected error in worker for App modeManage:
2024-11-07 23:23:39.202676 WARNING modeManage: Worker Ags: {'id': '816a466e04b541b6adf8ac38ffefd5d0', 'name': 'modeManage', 'objectid': 'd6fdada3a0104f528328fb504626db5d', 'type': 'state', 'function': <bound method ModeManagement.presenceChange of <modeManagement.ModeManagement object at 0x7fd7cafaa290>>, 'attribute': 'state', 'entity': 'person.micke', 'new_state': 'not_home', 'old_state': 'home', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2024-11-07 23:23:39.202874 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:23:39.203556 WARNING modeManage: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1045, in worker
    funcref(
  File "/config/apps/modeManagement.py", line 581, in presenceChange
    for door in self.MQTT_door_lock:
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModeManagement' object has no attribute 'MQTT_door_lock'

2024-11-07 23:23:39.203749 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:45:00.080980 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:45:00.087431 WARNING modeManage: Unexpected error in worker for App modeManage:
2024-11-07 23:45:00.092488 WARNING modeManage: Worker Ags: {'id': '816a466e04b541b6adf8ac38ffefd5d0', 'name': 'modeManage', 'objectid': 'd6fdada3a0104f528328fb504626db5d', 'type': 'state', 'function': <bound method ModeManagement.presenceChange of <modeManagement.ModeManagement object at 0x7fd7cafaa290>>, 'attribute': 'state', 'entity': 'person.micke', 'new_state': 'home', 'old_state': 'not_home', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2024-11-07 23:45:00.094300 WARNING modeManage: ------------------------------------------------------------
2024-11-07 23:45:00.097938 WARNING modeManage: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1045, in worker
    funcref(
  File "/config/apps/modeManagement.py", line 530, in presenceChange
    self.unlockDoor()
  File "/config/apps/modeManagement.py", line 398, in unlockDoor
    for door in self.MQTT_door_lock:
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModeManagement' object has no attribute 'MQTT_door_lock'

2024-11-07 23:45:00.098523 WARNING modeManage: ------------------------------------------------------------

```

**Comment by pointlevel** [comment]
Yes, that was the case. Too fast and eager to test new features :)
